name: Preview comment
on:
  pull_request_target:
    types:
      - opened
permissions:
  contents: read
  pull-requests: write
jobs:
  post:
    name: Post
    if:
      github.event.pull_request.base.repo.full_name == 'everyleaf/hotwire_ja'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Comment
        env:
          GH_TOKEN: ${{ github.token }}
          PR_REPOSITORY: ${{ github.event.pull_request.base.repo.full_name }}
          FORK_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          configure_url="https://github.com/everyleaf/hotwire_ja/blob/main/README.md#プレビュー"
          fork_owner=${FORK_REPOSITORY%/*}
          fork_repository=${FORK_REPOSITORY#*/}
          cat <<COMMENT > body.md
          Preview: https://${fork_owner}.github.io/${fork_repository}

          See ${configure_url} how to configure preview on fork.
          COMMENT
          gh pr comment ${PR_NUMBER} \
            --body-file body.md \
            --repo ${PR_REPOSITORY}
